### ISSUE TITLE
Left leg "Hawk Talon" markings are not showing in side view

### ISSUE THREAD

**Issue by Neliahawk** [SPLURT-Station/S.P.L.U.R.T-tg#308]
### Client Version:

516.1659

### Issue Summary:

the "Hawk talon" markings on the left leg dont show when looking to the right and is visible on the right leg instead.
https://files.catbox.moe/w576yo.jpg
https://files.catbox.moe/2qynvi.jpg
https://files.catbox.moe/xw9g2u.jpg
https://files.catbox.moe/hr6hg6.jpg

(this marking is broken like that since ages. i.e. old splurt.)

### Round ID:

7920

### Test Merge Information:

- [Packing peanuts](https://github.com/SPLURT-Station/S.P.L.U.R.T-tg/pull/284)
- [[DNM] Bunch of Bug Fixes](https://github.com/SPLURT-Station/S.P.L.U.R.T-tg/pull/234)

### Reproduction Steps:

go to character editor
add "hawk talon" to both legs
rotate character... notice in the looking right sideview one leg shows skin color.
remove right leg hawk talons so they just on the left leg.
rotate around and see that its on the right leg applied in the looking right sideview.

**Comment by Krashly** [comment]
Fixed!

**Comment by Neliahawk** [comment]
i think this is still broken. might need to take a look at this again.
i tried to mark the relevant areas in yellow.

Left Leg:
this is fine from the front.
https://files.catbox.moe/btk194.jpg

this side view should show one pixel along the whole back leg there, from the top pixel that is there to the feet.
https://files.catbox.moe/nrmxg2.jpg

back view is fine
https://files.catbox.moe/c9jhjf.jpg

this side view has a rogue pixel on the back there that shouldnt be there.
https://files.catbox.moe/wxevp8.jpg

Right Leg:
front view is fine.
https://files.catbox.moe/muqz42.jpg

similar rogue pixel that shouldnt be there.
https://files.catbox.moe/tb56o8.jpg

back view is fine
https://files.catbox.moe/6phia8.jpg

this is the most broken... it should just be the one pixel line there and not all the other areas.
https://files.catbox.moe/u45dzf.jpg
so basically leave the leftmost pixels and remove the others.
and then this one can be flipped and used above for the other leg too https://files.catbox.moe/nrmxg2.jpg
